#!/bin/bash
echo "export COVERITY_CLUSTER_NAME=$(terraform output -raw aks_cluster_name)"
echo "export COVERITY_CLUSTER_REGION=$(terraform output -raw azure_resource_group_location)"
echo "export COVERITY_AZ_RESOURCE_GROUP=$(terraform output -raw azure_resource_group_name)"
echo "export COVERITY_PGHOST=$(terraform output -raw db_instance_address)"
echo "export COVERITY_PGUSER=$(terraform output -raw db_instance_username)"
echo "export COVERITY_PGPASSWORD=$(terraform output -raw db_master_password)"
echo "export COVERITY_AZ_BUCKET_NAME=$(terraform output -raw storage_bucket_name)"
echo "export COVERITY_AZ_STORAGE_ACCOUNT_NAME=$(terraform output -raw storage_account_name)"
echo "export COVERITY_AZ_STORAGE_ACCOUNT_KEY=$(terraform output -raw storage_access_key)"

echo "export COVERITY_CACHE_BUCKET_NAME=$(terraform output -raw coverity_cache_bucket_name)"
echo "export COVERITY_REDIS_HOST=$(terraform output -raw redis_host)"
echo "export COVERITY_REDIS_PORT=$(terraform output -raw redis_port)"
echo "export COVERITY_REDIS_PASSWORD=$(terraform output -raw redis_password)"
echo "export COVERITY_AZURE_ENDPOINT=$(terraform output -raw storage_account_endpoint)"
